---
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
- ros_topic_name: "/imu"
  gz_topic_name: "/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "ignition.msgs.IMU"
  direction: "GZ_TO_ROS"
- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/demo/model/h1_ign/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS
- ros_topic_name: "/tf"
  gz_topic_name: "/model/h1_ign/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
- ros_topic_name: "/tf_static"
  gz_topic_name: "/model/h1_ign/pose_static"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS  
- gz_topic_name: /model/h1_ign/odometry
  ros_topic_name: /h1_ign/odometry
  gz_type_name: ignition.msgs.Odometry
  ros_type_name: nav_msgs/msg/Odometry
  direction: GZ_TO_ROS
- ros_topic_name: "/left_hip_yaw_joint_cmd"
  gz_topic_name: "/model/h1_ign/joint/left_hip_yaw_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/left_hip_pitch_joint_cmd"
  gz_topic_name: "/model/h1_ign/joint/left_hip_pitch_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/left_hip_roll_joint_cmd"
  gz_topic_name: "/model/h1_ign/joint/left_hip_roll_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/left_knee_joint_cmd"
  gz_topic_name: "/model/h1_ign/joint/left_knee_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/left_ankle_pitch_joint_cmd"
  gz_topic_name: "/model/h1_ign/joint/left_ankle_pitch_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/left_ankle_roll_joint_cmd"
  gz_topic_name: "/model/h1_ign/joint/left_ankle_roll_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/right_hip_yaw_joint_cmd"
  gz_topic_name: "/model/h1_ign/joint/right_hip_yaw_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/right_hip_pitch_joint_cmd"
  gz_topic_name: "/model/h1_ign/joint/right_hip_pitch_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/right_hip_roll_joint_cmd"
  gz_topic_name: "/model/h1_ign/joint/right_hip_roll_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/right_knee_joint_cmd"
  gz_topic_name: "/model/h1_ign/joint/right_knee_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/right_ankle_pitch_joint_cmd"
  gz_topic_name: "/model/h1_ign/joint/right_ankle_pitch_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/right_ankle_roll_joint_cmd"
  gz_topic_name: "/model/h1_ign/joint/right_ankle_roll_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/torso_joint_cmd"
  gz_topic_name: "/model/h1_ign/joint/torso_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/left_shoulder_pitch_joint_cmd"
  gz_topic_name: "/model/h1_ign/joint/left_shoulder_pitch_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/left_shoulder_roll_joint_cmd"
  gz_topic_name: "/model/h1_ign/joint/left_shoulder_roll_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/left_shoulder_yaw_joint_cmd"
  gz_topic_name: "/model/h1_ign/joint/left_shoulder_yaw_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/left_elbow_joint_cmd"
  gz_topic_name: "/model/h1_ign/joint/left_elbow_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/left_wrist_roll_joint_cmd"
  gz_topic_name: "/model/h1_ign/joint/left_wrist_roll_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/left_wrist_pitch_joint_cmd"
  gz_topic_name: "/model/h1_ign/joint/left_wrist_pitch_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/left_wrist_yaw_joint_cmd"
  gz_topic_name: "/model/h1_ign/joint/left_wrist_yaw_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/right_shoulder_pitch_joint_cmd"
  gz_topic_name: "/model/h1_ign/joint/right_shoulder_pitch_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/right_shoulder_roll_joint_cmd"
  gz_topic_name: "/model/h1_ign/joint/right_shoulder_roll_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/right_shoulder_yaw_joint_cmd"
  gz_topic_name: "/model/h1_ign/joint/right_shoulder_yaw_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/right_elbow_joint_cmd"
  gz_topic_name: "/model/h1_ign/joint/right_elbow_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/right_wrist_roll_joint_cmd"
  gz_topic_name: "/model/h1_ign/joint/right_wrist_roll_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/right_wrist_pitch_joint_cmd"
  gz_topic_name: "/model/h1_ign/joint/right_wrist_pitch_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/right_wrist_yaw_joint_cmd"
  gz_topic_name: "/model/h1_ign/joint/right_wrist_yaw_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ